"""
Django settings for usda_fns_ingestor project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%*62cyo2f=qeo@fxf1veh8ns@=ea6ft70bqaj+q^end45w3y@_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '.cloud.gov',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'data_ingest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usda_fns_ingestor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'usda_fns_ingestor.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='postgres:///usda_fns_ingestor')
}
#    default='postgres+asyncpg:///usda_fns_ingestor')}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

UPLOAD_COLUMNS = [
    '_16_State_ID',
    '_16_SFA_ID',
    '_16_TypeSFA_Public',
    '_16_TypeSFA_Private',
    '_16_School_Year_From',
    '_16_School_Year_To',
    '_16_SFA_Name',
    '_16_SFA_City',
    '_16_SFA_Zip_Code',
    '_16_11A_nonrcci_schl',
    '_16_11B_nonrcci_stud',
    '_16_12A_rcci_schl',
    '_16_12B_rcci_stud',
    '_16_12aA_rcci_day_schl',
    '_16_12aB_rcci_day_stud',
    '_16_12bA_rcci_nonday_schl',
    '_16_12bB_rcci_nonday_stud',
    '_16_21A_base23_schl',
    '_16_21B_base23_stud',
    '_16_22A_nonbase23_schl',
    '_16_22B_nonbase23_stud',
    '_16_22aB_nonbase23_free_stud',
    '_16_22bB_nonbase23_rp_stud',
    '_16_23A_cep_schl',
    '_16_23B_cep_stud',
    '_16_24A_altboth_schl',
    '_16_24B_altboth_stud',
    '_16_25A_altoneonly_schl',
    '_16_25B_altoneonly_stud',
    '_16_31_dc_notrequired',
    '_16_32B_dc_snap_stud',
    '_16_33B_dc_other_stud',
    '_16_34B_free_snapletter_stud',
    '_16_41A_free_doc_apps',
    '_16_41B_free_doc_stud',
    '_16_42A_free_inc_apps',
    '_16_42B_free_inc_stud',
    '_16_43A_rp_inc_apps',
    '_16_43B_rp_inc_stud',
    '_16_t1_tot_free',
    '_16_t2_tot_rp',
    '_16_51_exempt',
    '_16_52_verif_yes_before',
    '_16_52_verif_yes_after',
    '_16_52_verif_no',
    '_16_53_verif_type_standard',
    '_16_53_verif_type_alt1',
    '_16_53_verif_type_alt2',
    '_16_54_error',
    '_16_55_selected_apps',
    '_16_56_noverif_sfa',
    '_16_57A_confirmverf_apps',
    '_16_57B_confirmverf_stud',
    '_16_58AA_freecat1_r_nc_apps',
    '_16_58AB_freecat1_r_nc_stud',
    '_16_58AA_freecat2_r_rp_apps',
    '_16_58AB_freecat2_r_rp_stud',
    '_16_58AA_freecat3_r_paid_apps',
    '_16_58AB_freecat3_r_paid_stud',
    '_16_58AA_freecat4_n_paid_apps',
    '_16_58AB_freecat4_n_paid_stud',
    '_16_58BA_freeinc1_r_nc_apps',
    '_16_58BB_freeinc1_r_nc_stud',
    '_16_58BA_freeinc2_r_rp_apps',
    '_16_58BB_freeinc2_r_rp_stud',
    '_16_58BA_freeinc3_r_paid_apps',
    '_16_58BB_freeinc3_r_paid_stud',
    '_16_58BA_freeinc4_n_paid_apps',
    '_16_58BB_freeinc4_n_paid_stud',
    '_16_58CA_rp1_r_nc_apps',
    '_16_58CB_rp1_r_nc_stud',
    '_16_58CA_rp2_r_free_apps',
    '_16_58CB_rp2_r_free_stud',
    '_16_58CA_rp3_r_paid_apps',
    '_16_58CB_rp3_r_paid_stud',
    '_16_58CA_rp4_n_paid_apps',
    '_16_58CB_rp4_n_paid_stud',
    '_16_vc1_forcause'
]

DATA_INGEST = {
    'VALIDATORS': {
        # 'usda_fns.json': 'data_ingest.ingestors.GoodtablesValidator',
        'usda_sql_rules.yml': 'data_ingest.ingestors.SqlValidatorFailureConditions',
    },
    'STREAM_ARGS': {
        'sheet': 'Data',  # Uses the 'Data' sheet from workbook if .xlsx
        'headers': UPLOAD_COLUMNS,
    },
    'OLD_HEADER_ROW': 1,
}
