"""
Django settings for usda_fns_ingestor project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'data_ingest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usda_fns_ingestor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'usda_fns_ingestor.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='postgres:///usda_fns_ingestor')
}
#    default='postgres+asyncpg:///usda_fns_ingestor')}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', )
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

UPLOAD_COLUMNS = [
    'state_id',
    'sfa_id',
    'type_sfa_public',
    'type_sfa_private',
    'school_year_from',
    'school_year_to',
    'sfa_name',
    'sfa_city',
    'sfa_zip_code',
    'S11A_non_rcci_schl',
    'S11B_non_rcci_stud',
    'S12A_rcci_schl',
    'S12B_rcci_stud',
    'S12aA_rcci_day_schl',
    'S12aB_rcci_day_stud',
    'S12bA_rcci_non_day_schl',
    'S12bB_rcci_non_day_stud',
    'S21A_base_23_schl',
    'S21B_base_23_stud',
    'S22A_non_base_23_schl',
    'S22B_non_base_23_stud',
    'S22aB_non_base_23_free_stud',
    'S22bB_non_base_23_rp_stud',
    'S23A_cep_schl',
    'S23B_cep_stud',
    'S24A_alt_both_schl',
    'S24B_alt_both_stud',
    'S25A_alt_one_only_schl',
    'S25B_alt_one_only_stud',
    'S31_dc_not_required',
    'S32B_dc_snap_stud',
    'S33B_dc_other_stud',
    'S34B_free_snap_letter_stud',
    'S41A_free_doc_apps',
    'S41B_free_doc_stud',
    'S42A_free_inc_apps',
    'S42B_free_inc_stud',
    'S43A_rp_inc_apps',
    'S43B_rp_inc_stud',
    'T1_tot_free',
    'T2_tot_rp',
    'S51_exempt',
    'S52_yes_by_verif',
    'S52_yes_after_verif',
    'S52_no_verif',
    'S531_verif_type_standard',
    'S532_verif_type_alt_1',
    'S533_verif_type_alt_2',
    'S54_error',
    'S55_selected_apps',
    'S56_no_verif_sfa',
    'S57A_confirm_verf_apps',
    'S57B_confirm_verf_stud',
    'S58A1a_free_cat_r_nc_apps',
    'S58A1b_free_cat_r_nc_stud',
    'S58A2a_free_cat_r_rp_apps',
    'S58A2b_free_cat_r_rp_stud',
    'S58A3a_free_cat_r_paid_apps',
    'S58A3b_free_cat_r_paid_stud',
    'S58A4a_free_cat_n_paid_apps',
    'S58A4b_free_cat_n_paid_stud',
    'S58B1a_free_inc_r_nc_apps',
    'S58B1b_free_inc_r_nc_stud',
    'S58B2a_free_inc_r_rp_apps',
    'S58B2b_free_inc_r_rp_stud',
    'S58B3a_free_inc_r_paid_apps',
    'S58B3b_free_inc_r_paid_stud',
    'S58B4a_free_inc_n_paid_apps',
    'S58B4b_free_inc_n_paid_stud',
    'S58C1a_rp_r_nc_apps',
    'S58C1b_rp_r_nc_stud',
    'S58C2a_rp_r_free_apps',
    'S58C2b_rp_r_free_stud',
    'S58C3a_rp_r_paid_apps',
    'S58C3b_rp_r_paid_stud',
    'S58C4a_rp_n_paid_apps',
    'S58C4b_rp_n_paid_stud',
    'VC1_for_cause'
]

DATA_INGEST = {
    'VALIDATORS': {
        'usda_fns.json': 'data_ingest.ingestors.GoodtablesValidator',
        # None: 'data_ingest.ingestors.GoodtablesValidator',
        'usda_sql_rules.yml': 'data_ingest.ingestors.SqlValidatorFailureConditions',
    },
    'STREAM_ARGS': {
        'sheet': 'Data',  # Uses the 'Data' sheet from workbook if .xlsx
        'headers': 1,  # UPLOAD_COLUMNS,
    },
    # 'OLD_HEADER_ROW': 1,
}
